# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7060594ed6c451dfa3a3998c62908b38d4b41eb2b2958d82d25755329882276ab192157ebc996d0eb7cc73897c8791239fea8dc4bfe8d3de2eac72ba4107ff66

test:
  secret_key_base: 90278ede552efe65c297d0b9df4092515fc2d6bd08fe3ace2cace1226314c7c0d121bd8da797e50567ba77c919f46182e2832bfb49f695df094e5a17c5d55f03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
